name: Build and upload to Maestro Cloud (Native iOS)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
      - name: Install dependencies
        run: npm install

      - name: Cache data
        uses: actions/cache@master
        with:
          path: |
            ./ios/Pods
            ./ios/my_build
          key: ${{ runner.os }}-derived-data-${{ hashFiles('ios/Podfile.lock') }}
      - if: ${{ steps.derived-data-cache.outputs.cache-hit != 'true' }}
        name: Build app for simulator
        working-directory: ios
        env:
          DERIVED_DATA_PATH: my_build
        run: |
          pod install
          xcrun xcodebuild \
            -scheme "exampleNative" \
            -workspace "exampleNative.xcworkspace" \
            -configuration "Release" \
            -sdk "iphonesimulator" \
            -destination "generic/platform=iOS Simulator" \
            -derivedDataPath "${{ env.DERIVED_DATA_PATH }}"

      - uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: './ios/my_build/Build/Products/Release-iphonesimulator/exampleNative.app'


